azure:
  free_disk_space: true
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
remote_ci_setup:
  - rattler-build=0.41           # workaround for https://github.com/prefix-dev/rattler-build/issues/1701
